### ISSUE TITLE
update your profile pictures

### ISSUE THREAD

**Issue by arasbm** [akash7429/OnlyOnlyThinkAndDo#8]
comment here once you update your profile picture. This is for everyone in the team. Please use a picture of yourself so I can easily see who is doing what

- [x] @shahk0927 
- [x] @akash7429 
- [x] @FarihaPenon 
- [x] Harmanpreet

**Comment by akash7429** [comment]
done.

**Comment by arasbm** [comment]
Good looking team! Thanks! :)
